# Data structures

# Some (object)

Text description
more description seen, this might work or not?

## Properties
- list (array[Some Other Object], fixed-type)
- str (array)

# Some Other Object
+ item one
