# Data structures

# Some (object)

Text description.

## Properties

- obj1
  This is description including the line below
  - comment

- obj2
  - nested
    This still is description but the stuff below is not.
    - comment

- obj3
  - nested1
    This still is description and the line below is desciption too.
      - comment
